include:
  # 1. ПРОШИВКА ДЛЯ ДОНГЛА
  - board: nice_nano_v2
    shield: lily58_left
    snippet: studio-rpc-usb-uart
    # Добавляем флаги прямо в билд, чтобы не создавать файлы .conf
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
    artifact-name: lily58_dongle

  # 2. ПРОШИВКА ДЛЯ ЛЕВОЙ ПОЛОВИНЫ
  - board: nice_nano_v2
    shield: lily58_left
    # Отключаем роль центрального устройства, чтобы она стала периферией
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lily58_left

  # 3. ПРОШИВКА ДЛЯ ПРАВОЙ ПОЛОВИНЫ
  - board: nice_nano_v2
    shield: lily58_right
    artifact-name: lily58_right

  # 4. СБРОС (на случай проблем с коннектом)
  - board: nice_nano_v2
    shield: settings_reset
